language: node_js
sudo: false
node_js:
  - 'stable'
  - "0.11"

install:
- npm install -g bower
- npm install -g gulp
- bower install
- npm install
- npm run build
script: gulp

after_success:
  - bash deploy.sh

env:
  global:
  - GH_REF: github.com/matt3188/Curriculum-vitae
  - secure: "iAvZuesApM3ks6zA0ME/IJ049dkpuYybJe7x3ZzJVShJwmxlj/NodFUDklXbMhMyTnqBqtIH5fJWmQGS+3g2sUyGTGF3GPVf7JIapKdq1hsaftaRkSDi1qpvsNsM0vFwu8YJd9ZgTNmE/7CExUfoXzlBvlz8lRhE3jRZyuOdRh/i/FGmjI2tYpLIh7j6biwoYxZSCg5RmVtyFID/5O1iLyFg1PDZxQJqxTabhw35mmtHJm0zjVB+98HG39N7g9qicsNHLIQ2woA6lcOE3hIGf6mn5FCouJnOB3g+Rh2G1s+ItWZwVQqYmKhNfE8uZqd5bwqSRIvprhAZPrYt/mIDvfvHJzGr7zeMShkwO5AjMGMD2mQQpfHB3xS7nlu51si5Q4owH/45KC5G7FBhx9wuYYyKcQFcwXnH8RWc2CsfHN55ZeOa1G/c9X4zD+c24rCBjJqVbU3TxewicEc6Ipk21CaRpCFmm+tgKBkTRKE4n9vwgbDQRg5d/zyKRj7bdBJgY3vS+HTL/S/TP6Cwnt99R4RNqxQC/cL+QIt7XWtmTo3E5TVjxXdLp+VJ4ffUPCmsQTRUq2rroGVnw0w0YC4aPrBi4Lm8s3wzX7MKBNTpRBjyB/Bv3+BxWVyOLfL4iwbm3lHbqlJryGZgVj1b1AaPTqeZUa5bcFbcc1d235jQEMs="
